### ISSUE TITLE
open discussions

### ISSUE THREAD

**Issue by MrClogsworthYT** [Manux123/FNF-Cool-Engine#10]
so the issues won't be spammed with random questions

**Comment by Juanen100** [comment]
what do u mean?

**Comment by Juanen100** [comment]
ok nvm i found a docs from GitHub of how to setup it

**Comment by Juanen100** [comment]
Ok... Since I'm not the owner I'm asking @Manux123 to open it

**Comment by MrClogsworthYT** [comment]
> Ok... Since I'm not the owner I'm asking @Manux123 to open it

kay
