### ISSUE TITLE
small request from the original funkin android co-creator

### ISSUE THREAD

**Issue by zacksgamerz** [Manux123/FNF-Cool-Engine#23]
yo cool engine and all but it'd be p awesome if you guys add credits for luckydog? He made the hx files for virtual controls + he is p underrated. Nice engine tho!

**Comment by MrClogsworthYT** [comment]
> yo cool engine and all but it'd be p awesome if you guys add credits for luckydog? He made the hx files for virtual controls + he is p underrated. Nice engine tho!

aight thanks zack i forgor lol

**Comment by zacksgamerz** [comment]
thank u!

**Comment by MrClogsworthYT** [comment]
> thank u!

np
