### ISSUE TITLE
[BUG] source/states/VideoState.hx:50: characters 49-51 : Unexpected ==

### ISSUE THREAD

**Issue by YumDev21** [Manux123/FNF-Cool-Engine#36]
source/states/VideoState.hx:50: characters 49-51 : Unexpected ==

`    private inline function endVideo(?kill:bool == true):Void{
        if(kill)video.kill();
        FlxG.sound.music.stop();
        LoadingState.loadAndSwitchState(nextState);
    }`

That's the part that is throwing the error

**Comment by MrClogsworthYT** [comment]
yh tryna fix this

**Comment by YumDev21** [comment]
Hey guys, I almost fixed the problem. If you can tell me where videoPath is stored then I might be able to fix it

**Comment by YumDev21** [comment]
Ill send a pull request for the fixed code so far but if you guys can fix the rest then great job
