### ISSUE TITLE
to juan

### ISSUE THREAD

**Issue by Jotaro-Gaming** [Manux123/FNF-Cool-Engine#44]
@Juanen100 yo my main discord got hacked
my new discord account is Jotaro Gaming#4072
please add me
and add me to the group too
we havent made an update in ages dude /:

**Comment by IvoryXL** [comment]
Yo can I add you too?

**Comment by IvoryXL** [comment]
@MrClogsworthYT I added you

**Comment by MrClogsworthYT** [comment]
@Manux123 u too
