### ISSUE TITLE
[PLAYTEST RESULTS]

### ISSUE THREAD

**Issue by XuelDev** [Manux123/FNF-Cool-Engine#46]
So... I tried out the Cool Engine after the most recent update.

Firstly, the TitleState introduction doesn't work. Secondly, in song the Girlfriend animation is not working
Next, the mods system might need a revamp tbh i think that its a bit buggy. Like i mean it. First the songs don't load then some of the sprites are glitchy and more.

**Comment by MrClogsworthYT** [comment]
yeah its a bit buggy but its understandable as we are still in beta will keep this open to remember!

**Comment by XuelDev** [comment]
Fixed most of these issues
