### ISSUE TITLE
the note skins arn't working 

### ISSUE THREAD

**Issue by Jonnycatmeow** [Manux123/FNF-Cool-Engine#7]
the note skins arn't working

**Comment by Jonnycatmeow** [comment]
on the newer one on the release

**Comment by Juanen100** [comment]
Could you please provide more details?

**Comment by Juanen100** [comment]
Never mind I think I found whats the issue is. You are talking about just when the game crashes when you enable the custom skins, right?

**Comment by Jonnycatmeow** [comment]
i meant for the arrows and the circles

**Comment by Jonnycatmeow** [comment]
for macos

**Comment by Juanen100** [comment]
But we didnt build for mac os yet, and i alredy fixed what you mean

**Comment by susyboy23** [comment]
haha, the arrow shit is broken again, in the week 6 XD

**Comment by susyboy23** [comment]
it just dont load the song in any skin, so bruh

**Comment by Jonnycatmeow** [comment]
nevermind
